### PR TITLE
CN translation（lang，readme，how to play）

### PR DESCRIPTION
**Pull request by Cryghast**

### CODE REVIEW

**Comment by Sollace** [comment]
Why are you changing introduction.json? Can that be reverted please.

**Comment by Cryghast** [comment]
>

My parter translated the introduction.json before. He changed the original introduction.json and committed it. I changed it back(simply copy the original json file's text and cover it up) ,so I thought the two files should be identical.

Well then, I'll consider use the original file to replace it, for good.

**Comment by Cryghast** [comment]
> Why are you changing introduction.json? Can that be reverted please.

It's done

**Comment by Cryghast** [comment]
我希望转载此Unicopia 至mcmod.cn，请问您可以接受吗？I want to publish the Unicopia to ''mcmod.cn'' .Can you accept?

image

**Comment by MimzyFang** [comment]
I don't know what @Sollace thinks about publishing it there but I personally would say only if it gets published though the CI/CD here on this GitHub repository

**Comment by Cryghast** [comment]
> I don't know what @Sollace thinks about publishing it there but I personally would say only if it gets published though the CI/CD here on this GitHub repository
IMG_2602

I'm thinking the way like this, as mine little pony mod has been 'published' before(the people who created this page didn't offer their own download source , though). And I'm both new in GitHub and mcmod, I don't know if it is correct  to use 'publish' word, as mcmod.cn is more like a mod wiki, and I just want to spread Unicopia? In case I may need someone's permission to create a page on it.

**Review by Sollace — APPROVED** [review]

**Comment by Sollace** [comment]
Is this ready to merge or do you want to make more changes?

**Comment by Cryghast** [comment]
> Is this ready to merge or do you want to make more changes?

It's done, ready to merge, then we will keep tracking and update the lang file

**Pull request merged**
