### PR TITLE
Add auto build

### PR DESCRIPTION
**Pull request by Fangliding**
Automatic is 20% cooler than manual
~~In fact I found #191 when I tried to make this~~

### CODE REVIEW

**Comment by Sollace** [comment]
What is the "Upload Mod" part of this doing?

**Comment by Fangliding** [comment]
> What is the "Upload Mod" part of this doing?

After building, you may need to install it in the game for testing. This step will upload the built jar to artifacts for download
For example, this is in my repo(https://github.com/Fangliding/Unicopia/actions/runs/6220061179). You can see mod under Artifacts and you can download it directly if needed

**Comment by Fangliding** [comment]
But there is a problem. Sometimes build will fail due to to unable to get source(https://github.com/Fangliding/Unicopia/actions/runs/6221116537/job/16882470342)
This happens randomly, it might be fine if run it again. Perhaps It is needed to add a feature to try again when it fails

**Comment by Sollace** [comment]
Alright thanks, however I'd prefer to use what already works for my other projects. (Also not keen on publishing to github's artefacts)

I had already started setting up Modrinth publishing before this PR, so I went ahead and did the last few things to get that working and added the needed gh actions to make it work.

**Pull request closed without merging**
