### PR TITLE
Cancel enchantment removal to...

### PR DESCRIPTION
**Pull request by PoneyClairDeLune**
... fix the fishing enchantment problems.

### CODE REVIEW

**Comment by Sollace** [comment]
What is this trying to fix?

**Comment by PoneyClairDeLune** [comment]
Before (since 1.3.9+1.20.1, captured on 26 Nov 2024):

image

The enchanted books obtained from fishing are all either blank or with Clingy III only. Affects both vanilla fishing and modded fishing (e.g. Nether fishing in Nether Depth Upgrades).

After fixing:

image

The bug is no longer there.

**Comment by PoneyClairDeLune** [comment]
Only patched out the place where the removal is done, however for a full fix for `1.20.1`, the following files will all need some attention. Some of the files simply do not exist in the latest codebase.

- `src/main/java/com/minelittlepony/unicopia/item/enchantment/CustomEnchantableItem.java`
- `src/main/java/com/minelittlepony/unicopia/mixin/MixinEnchantment.java`
- `src/main/java/com/minelittlepony/unicopia/mixin/MixinEnchantmentHelper.java`

You can debug the enchanted books obtained from fishing easily with `/give @s barrel{BlockEntityTag:{LootTable:"minecraft:gameplay/fishing/treasure"}}` instead of fishing constantly.

**Comment by PoneyClairDeLune** [comment]
Closing this PR for now as it's only intended as a temporary solution.

**Comment by Sollace** [comment]
`/loot give @p fish minecraft:gameplay/fishing/treasure ~ ~ ~`

image

**Pull request closed without merging**
